# Generated by Django 5.2.1 on 2025-05-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='std_address',
            field=models.TextField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
