# Generated by Django 5.2.1 on 2025-05-24 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_admission_std_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='std_address',
        ),
    ]
